### ISSUE TITLE
View all so that the user can see what tasks they have 'In Progress' and have 'Completed'

### ISSUE THREAD

**Issue by Eliwash73** [xlab-classes/cse442-spring2022-team-terms-co#21]
**Task tests**

_Test 1:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed id=1’
6. send the message ‘view’ to the bot
7. verify in the terminal on replit that the toDo dictionary looks like this:
    {0:2,  2: (’workout ’, ‘5pm’), 3: (’eat dinner’, ‘6pm’)} 
8. verify in the terminal on replit that the completed dictionary looks like this:
    {1: (’cook ’, ‘4pm’)}
    

_Test 2:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed id=1’
6. send the message ‘completed id=2’
7. send the message ‘completed id=3’
8. send the message ‘view’ to the bot
9. verify in the terminal on replit that the toDo dictionary looks like this:
    {0:0}
10. verify in the terminal on replit that the completed dictionary looks like this:
    {1: (’cook ’, ‘4pm’),  2: (’workout ’, ‘5pm’), 3: (’eat dinner’, ‘6pm’)}

**Comment by amoghjos** [comment]
It is missing sprint label and should not use sprints section

**Comment by amoghjos** [comment]
Is this task completed?
