### ISSUE TITLE
Get help for messages format by sending "help".

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#23]
**Task Tests:**

Test 1: Ensuring Help Works and is Well Formatted

1. Go to https://replit.com/@SnigdhaMotadaka/todobot#main.py
2. Press the "Run" button
3. Open the discord server where the bot resides
4. Type help in the server chat
5. Ensure that a help message appears and that the message is well-formatted and descriptive enough

**Comment by amoghjos** [comment]
Task description is not needed and dependancy is missing
