### ISSUE TITLE
Delete a task by sending a message in the form "delete"  followed by task name to remove a task from progress or completed

### ISSUE THREAD

**Issue by tanviekirane** [xlab-classes/cse442-spring2022-team-terms-co#26]
Task: Delete a task from progress or completed if it exists.

Task tests:

**Progress:**

Test 1:

1. Go to the discord server containing the bot.
2. Type ‘remind me to eat at 7 pm'
3. The bot sends a random affirmative message with taskid=1
4. Now type ‘delete 1'
5. Verified by bot's response of "Task has been successfully deleted!"

Test 2:

1. Go to the discord server containing the bot.
2. Type ‘remind me to eat at 7 pm'
3. The bot sends a random affirmative message with taskid=1
4. Now type ‘delete 5'
5. Verified by bot's response of "No such task exists"

********************************************************************

**Completed**

Test 3:

1. Go to the discord server containing the bot.
2. Type ‘remind me to eat at 7 pm'
3. The bot sends a random affirmative message (with taskid)
4. Type 'view' and note down the taskid=1
5. Type "completed id=1"
6. Now type ‘delete 1'
7. Verified by bot's response of "Task has been successfully deleted!"

Test 4:

1. Go to the discord server containing the bot.
2. Type ‘remind me to sleep at 9 pm'
3. The bot sends a random affirmative message (with taskid)
4. Type 'view' and note down the taskid=1
5. Type "completed id=1"
6. Now type ‘delete 5'
7. Verified by bot's response of "No such task exists"

**Comment by amoghjos** [comment]
Why are there 2 sections?
