### ISSUE TITLE
As a scheduler, I want to be reminded to do my tasks at a particular time

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#27]
**Task Test:**

Test 1: Testing Add

Go to the local code in my computer
Run the code.
Open the discord server where the bot resides.
Schedule a task.
Now, wait for the bot to send you a reminder of the task you just edited.
Test 2: Testing Edit

Go to the local code in my computer
Run the code.
Open the discord server where the bot resides.
Schedule a task.
Edit the task scheduled.
Now, wait for the bot to send you a reminder of the task you just scheduled.

**Comment by amoghjos** [comment]
Number ordering is missing
