### ISSUE TITLE
As a scheduler, I want to delete a task by sending a message in the form: "delete task..." so that I can remove the task from my task list if it exists in progress or completed

### ISSUE THREAD

**Issue by tanviekirane** [xlab-classes/cse442-spring2022-team-terms-co#28]
Acceptance Tests:

_Test 1:_
1. Go to the discord server containing the bot.
2. Type ‘remind me to eat at 7 pm'
3. The bot sends a random affirmative message
4. Now type ‘delete remind me to eat'
5. Verified by bot's response of "Task has been successfully deleted!"

_Test 2:_
1. Go to the discord server containing the bot.
2. Type ‘remind me to eat at 7 pm'
3. The bot sends a random affirmative message
4. Now type ‘delete remind me to sleep'
5. Verified by bot's response of "No such task exists"

_Test 3:_
1. Go to the discord server containing the bot.
2. Type ‘remind me to eat at 7 pm'
3. The bot sends a random affirmative message (with taskid)
4. Type 'view' and note down the taskid
5. Type completed id=(use the id from above)
6. Now type ‘delete remind me to eat'
7. Verified by bot's response of "Task has been successfully deleted!"

_Test 4:_
1. Go to the discord server containing the bot.
2. Type ‘remind me to sleep at 9 pm'
3. The bot sends a random affirmative message (with taskid)
4. Type 'view' and note down the taskid
5. Type completed id=(use the id from above)
6. Now type ‘delete remind me to eat'
7. Verified by bot's response of "No such task exists"

**Comment by tanviekirane** [comment]
Acceptance Tests:

Test 1:

Go to the discord server containing the bot.
Type ‘remind me to eat at 7 pm'
The bot sends a random affirmative message
Now type ‘delete remind me to eat'
Verified by bot's response of "Task has been successfully deleted!"
Test 2:

Go to the discord server containing the bot.
Type ‘remind me to eat at 7 pm'
The bot sends a random affirmative message
Now type ‘delete remind me to sleep'
Verified by bot's response of "No such task exists"

**Comment by amoghjos** [comment]
Hi @tanviekirane, view isn't working tho...

**Comment by amoghjos** [comment]
@tanviekirane mentioned that view is completed so I'll test it in the next meeting
