### ISSUE TITLE
message sent back from view is formatted to clearly see which tasks are in progress and completed

### ISSUE THREAD

**Issue by Eliwash73** [xlab-classes/cse442-spring2022-team-terms-co#29]
*Task tests:*

_Test 1:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. type view
5. verify the response message looks like this
![Untitled.png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/e4ed3ef0-1146-4114-aa08-93373ac5aad0)
   

_Test 2:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Send several tasks:
    1. ‘remind me to eat dinner at 4pm’
5. type view
6. verify the response message looks like this
![Untitled (1).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/4da7f1fa-f21d-43be-9c12-36a446c17475)
_Test 3:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Send several tasks:
    1. ‘remind me to eat dinner at 4pm’
5. type completed id=4
6. type view
7. verify the response message looks like this
![Untitled (2).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/9669ea46-0371-400c-ad15-d75b4a5c3a46)

_Test 4:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Send several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
    4. ‘remind me to clean my room at 12pm’
5. send the message ‘completed id=1’
6. send the message ‘completed id=2’
7. type view
8. verify the response message looks like this
![Untitled (4).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/e2ce1947-a479-423a-a6d3-3dd96260b8a2)

**Comment by amoghjos** [comment]
The title is kinda vague. How can we validate like it's more user friendly? Please mention more specifics of this task on what was completed.
