### ISSUE TITLE
As a scheduler, I want to add a task so that I can send a message in the form of a sentence starting with "remind me to..." and have the bot ask me at what time

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#30]
Acceptance Test:

1) Go to discord developer portal
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/55bd00d9-38c5-4949-9770-9c445996bd9c)
2) Connect to the reminder bot (named testbot123456789)

Acceptance Tests:

**Test 1:**

1) Go to discord developer portal
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/55bd00d9-38c5-4949-9770-9c445996bd9c)
2) Connect to the reminder bot (named testbot123456789)
3) Run main.py
4) Go to discord server with reminder bot deployed
5) Send a message to the bot with a reminder
6) Format the reminder string to end with "...to" followed by the task to do which has the time to be reminded at
7) Confirm the bot recorded your task by looking out for a reply from the bot on the server

**Test 2:** 
1) Run main.py
2) Go to discord server with reminder bot deployed
3) Send a message to the bot with a reminder
4) Format the reminder string to end with "...to" followed by the task to do at a certain time
> the bot can handle most natural language formats of time ranging from 6:00pm, 7 am, 6 PM etc.

5) The bot will register the task and give the user the task ID for future reference. 

**Test 3:**

1) Go to discord developer portal
image.png
2) Connect to the reminder bot (named testbot123456789)
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/55bd00d9-38c5-4949-9770-9c445996bd9c)
3) Run main.py
4) Go to discord server with reminder bot deployed
5) Send a message to the bot with a reminder
6) Format the reminder string to end with "...to" followed by the task to do
7) The bot will ask at what time
8) Provide the time
9) Confirm the bot recorded your task by looking out for a reply from the bot on the server

**Comment by amoghjos** [comment]
There are multiple test 1 and no numbering for steps. Please revise your description

**Comment by amoghjos** [comment]
Hi @snigui, there are 2 steps (Go to discord developer portal && Connect to the reminder bot (named testbot123456789)) which seems repeated

**Comment by amoghjos** [comment]
Hi @snigui, the formate of this user story is incorrect as it's missing "so that..." part. Please make the changes

**Comment by snigui** [comment]
i made the changes
