### ISSUE TITLE
Edit task should accept flexible time formats. 

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#32]
**Task Tests:**

Test 1: Time Format - Spaces

1. Go to https://replit.com/@SnigdhaMotadaka/todobot#main.py.
2. Press the "Run" button.
3.Open the discord server where the bot resides.
4. Make sure that there has been at least one task scheduled. To make sure, simply type "view." If now tasks appear to be scheduled, simply type "remind me to ....(task)..." For example, type "remind me to sleep at 10:00pm".
5: Now, to edit that scheduled task, type "edit 1 : remind me to play soccer at 5:45 pm." Assuming there exist a task with the id 1 in the toDos dictionary, the task should be edited. Also, make sure there is a space between '5:45' and 'pm'
6: Verify that the task has been edited correctly by typing "view."

Test 2: Time Format - No Spaces

1. Go to https://replit.com/@SnigdhaMotadaka/todobot#main.py.
2. Press the "Run" button.
3.Open the discord server where the bot resides.
4. Make sure that there has been at least one task scheduled. To make sure, simply type "view." If now tasks appear to be scheduled, simply type "remind me to ....(task)..." For example, type "remind me to sleep at 10:00pm".
5: Now, to edit that scheduled task, type "edit 1 : remind me to play soccer at 5:45pm." Assuming there exist a task with the id 1 in the toDos dictionary, the task should be edited. Also, make sure there is no space between '5:45' and 'pm' this time.
6: Verify that the task has been edited correctly by typing "view."

**Comment by amoghjos** [comment]
the task description (change the edit method so that it accepts multiple time formats.) is not needed

**Comment by amoghjos** [comment]
Bug label should not be added as we're only limited to user story and sprint
