### ISSUE TITLE
Double addition: "remind me to" followed by "at"

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#37]
**Task Tests**

_Test 1:_

1. Go to discord developer portal
 ![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/8b87efce-5e70-4776-b37f-841a9ca75a28)
3. Connect to the reminder bot (named testbot123456789)
4. Run main.py
5. Go to discord server with reminder bot deployed
6. Send a message to the bot with a reminder
7. Format the reminder string to end with "...to" followed by the task to do 
8. Confirm bot asks for what time
9. Provide a time in the format of 6am, 8 PM, 09:19am etc.
10. Confirm the bot recorded your task by looking out for a reply from the bot on the server
11. Check that the TaskID is correctly incremented, with the first task starting with ID of 1.
12. Check that no TaskID is overwritten.

_Test 2:_
1. Go to discord developer portal
 ![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/8b87efce-5e70-4776-b37f-841a9ca75a28)
3. Connect to the reminder bot (named testbot123456789)
4. Run main.py
5. Go to discord server with reminder bot deployed
6. Send a message to the bot with a reminder
7. Send time message in any other format not in time format (eg: 6am, 9:00AM)
8. Check that invalid format message is sent

**Comment by amoghjos** [comment]
- It has the label of bug but we should be not using that
- the title of a task should not start with "Task test for" -- but rather something else

**Comment by amoghjos** [comment]
Hi @snigui,

- Please ensure that you are following the formate for the task description. Currently, it does not includes the title "Task tests" in bold and Test 1, 2, etc in italics

**Comment by snigui** [comment]
@amoghjos i made the changes to formatting! please let me know if this is all okay now
