### ISSUE TITLE
As a scheduler, I want to add a task to do so I send a message in the form: "remind me to..." or any other sentence starting with "remind me to..."  and containing "at..." followed by task to do at time so that I can add new tasks to do

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#4]
**Acceptance Tests:**

Test 1:
1) Go to discord developer portal
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/f2f56f28-a764-4a06-b9bb-87ff8a0c2088)
2) Connect to the reminder bot (named testbot123456789)
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/03242e93-c2d5-4181-8587-88e552a1b5db)
3) Run main.py 
4) Go to discord server with reminder bot deployed
5) Send a message to the bot with a reminder
6) Format the reminder string to end with "...to" followed by the task to do which has the time to be reminded at
7) Confirm the bot recorded your task by looking out for a reply from the bot on the server

**Comment by amoghjos** [comment]
You were not supposed to use sprints section
