### ISSUE TITLE
Task to convert the user's input into a standard time - Add & Edit

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#41]
**Task Test:**

**Test 1: Testing Add** 

- Go to the local code in my computer
- Run the code.
- Open the discord server where the bot resides.
- Schedule a task.
- Now, wait for the bot to send you a reminder of the task you just edited.

**Test 2: Testing Edit**

- Go to the local code in my computer
- Run the code.
- Open the discord server where the bot resides.
- Schedule a task.
- Edit the task scheduled. 
- Now, wait for the bot to send you a reminder of the task you just scheduled.

**Comment by amoghjos** [comment]
Hi @ramikham, please note that only I can move the task to closed, you can't move it by yourself, so keep that in mind for next time :)
