### ISSUE TITLE
Set up a server in cheshire and set up a table for session persistence

### ISSUE THREAD

**Issue by tanviekirane** [xlab-classes/cse442-spring2022-team-terms-co#45]
Setting up a server & set up a table to store user session info.

_Task test 1:_

1. ssh <your_ubid>@cheshire.cse.buffalo.edu
2. cd /web/CSE442-542/2022-Spring/
3. mysql -h oceanus -u your_ubit -p

![image.png](https://images.zenhubusercontent.com/620d58f42095133d54775b16/0e4b8247-620a-4e79-9fb3-2dfdf08a1a93)

**Comment by amoghjos** [comment]
Hi @tanviekirane, there are some information in the description which should be removed.

- "Snigdha and I are working in parallel for this task. Set up a server & set up a table to store user session info."
- "Research task: Test out whether the application runs on the server"
- Please recheck the formatting of the writing tasks tests and use numbered list
