### ISSUE TITLE
As a scheduler, I want to view all my tasks so I can see the tasks I have and haven't completed

### ISSUE THREAD

**Issue by Eliwash73** [xlab-classes/cse442-spring2022-team-terms-co#5]
**Acceptance Test**

*Test 1:*

1. Go to discord server with the bot enable
2. Type 'view' and press enter
3. Verify you got the messages: 
    ‘No tasks in progress type 'help' to learn how to add a task!’
    ‘No completed tasks type 'help' to learn how to complete a task!’
    
*Test 2:*

1. Go to discord server with the bot enable 
2. Add a task by sending ‘remind me to feed my fish at 11am’
3. Send the message ‘view’
4. Verify you got the messages: 
    ‘In Progress:
    ➼ ID:1|  feed my fish at 11am’
    ‘No completed tasks type 'help' to learn how to complete a task!’
    
*Test 3:*

1. Go to discord server with the bot enable 
2. Add a task by sending ‘remind me to feed my fish at 11am’
3. send the message completed id=1
4. Send the message ‘view’
5. Verify you got the messages: 
    'No tasks in progress type 'help' to learn how to add a task!’ 
    ‘Completed:
    feed my fish at 11am’

**Comment by amoghjos** [comment]
Is this user story completed?

**Comment by amoghjos** [comment]
Since this user story is carried to the sprint 2, it should have label "Sprint 2" in it
