### ISSUE TITLE
As a scheduler, I want to be able to verify that the cheshire server is connected so that I can use the discord bot

### ISSUE THREAD

**Issue by tanviekirane** [xlab-classes/cse442-spring2022-team-terms-co#51]
Acceptance Test

_Test 1:_

1. go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static/
2. we should see:
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/542b1b56-18b4-4800-8da8-c8dc849eba07)

as verification that the server is hosting the bot

_Test 2:_

1. Open discord & launch the server with the bot
2. Verify that bot is running by seeing a filled green circle (active symbol) for the bot
3. Also can be verified by typing 'remind me to eat at 7 pm' and getting an affirmative response from the bot

**Comment by amoghjos** [comment]
Hi @tanviekirane, this user story sounds more like a task: what benefit will the user receive by connecting to the server? If connecting to server is something critical to some functionality, you can mention these tasks under that specific user story.

**Comment by amoghjos** [comment]
Hi @tanviekirane, there is still "Tanvie's:" and "Snigdha's:" mentioned in the description, so please remove them and add some verification step at the end of the test
