### ISSUE TITLE
Connect to UB's cheshire server

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#58]
Acceptance Tests

_Test 1:_

1) go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static/
2) verify that the following is seen:

![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/acd6375f-03b9-4301-82e3-64a2f4da32ea)

**Comment by amoghjos** [comment]
incorrect task title

**Comment by snigui** [comment]
i updated the title
