### ISSUE TITLE
Shorten the "help" command.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#64]
**Task Tests**
1. Enter a discord server or create one.
2. Invite the discord bot (if it has already not been invited) to the server using link "https://discord.com/api/oauth2/authorizeclient_id=945410708848386169&permissions=75776&scope=bot%20applications.commands".
3. Type "help" and make sure it includes all the new features and how to use them.

**Comment by amoghjos** [comment]
Hi @ramikham, you have combined two separate tasks into 1 and it does not follows the style guide
