### ISSUE TITLE
As a (new) scheduler, I want my first interaction with the bot to be as simple as possible, so I want to have a written guide explains the bot's commands and its usage.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#65]
**Acceptance Test**

_Test: Viewing the User Manual_
1. Visit the "dev" branch in GitHub by clicking on the following link:
https://github.com/xlab-classes/cse442-spring2022-team-terms-co/tree/main.
2. The README.md should be viewable, which includes about, supported commands, and a walkthrough of how to use the bot.

**Comment by amoghjos** [comment]
Hi @ramikham, the title and description of the user story does not match. Moreover, it is an incorrect user story and does not follow style guide either

**Comment by amoghjos** [comment]
Hi @ramikham, you need to provide MAIN branch link
