### ISSUE TITLE
As a scheduler, I want to be able to mark some of my scheduled tasks as "Important" so that important tasks will be obvious on my schedule.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#66]
_Test 1: Marking a Task as Important_
1. Enter a discord server or create one.
2. Invite the discord bot (if it has already not been invited) to the server using link "https://discord.com/api/oauth2/authorizeclient_id=945410708848386169&permissions=75776&scope=bot%20applications.commands".
3. Schedule a task like "remind me to finish my homework at 11:00am".
4. Type "mark task 1 as important".
5. Type "view" and verify that the task has been labeled as important.

**Comment by amoghjos** [comment]
Hi @ramikham, the user story does not follow the style guide
