### ISSUE TITLE
Allow the user to label a specific task as important.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#67]
**Task Tests**

_Test 1: Marking a Scheduled Task as Important_
1. Run the bot.
2. Go to the server containing the bot.
3. Schedule some task(say "remind me to eat lunch at 1:54pm"). This task will have an ID of 1.
4. Mark that task by typing: :mark task 1 as important".
5. Type "view" and check that a red circle appears to the left of that task, indicating that it is "important".

_Test 2: Editing a Scheduled Task that is Marked as Important_
1. Run the bot.
2. Go to the server containing the bot.
3. Schedule some task(say "remind me to eat lunch at 1:54pm"). This task will have an ID of 1.
4. Mark that task by typing: :mark task 1 as important".
5. Type "view" and check that a red circle appears to the left of that task, indicating that it is "important".
6. Now edit that task by typing "edit task 1 : eat lunch at 2:31pm".
7. Now type "view" and make sure that the task is still labeled as "Important".

_Test 3: Marking an Important Task as Not Important_
1. Run the bot.
2. Go to the server containing the bot.
3. Schedule some task(say "remind me to eat lunch at 1:54pm"). This task will have an ID of 1.
4. Mark that task by typing: :mark task 1 as important".
5. Mark the task as not important by typing "mark task 1 as not important"
6. Type "view" and check that no red circle appears to the left of that task

_Test 4: listing Important Tasks_
1. Run the bot.
2. Go to the server containing the bot.
3. Schedule several tasks.
4. Mark some (but not all) of them as important.
5. Type "list important tasks".
6. Then, type "view".
7. Make sure that "list important tasks" shows a different list from that of "view."

**Comment by amoghjos** [comment]
Hi @ramikham, please fix the user story so that it follows the styleguide and perhaps attach a video recording which demo's the app
