### ISSUE TITLE
Create a user manual to simplify using the bot especially for new users.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#74]
**Task Test**

1. Go to GitHub.
2. Open the dev branch (the following is a link to it: https://github.com/xlab-classes/cse442-spring2022-team-terms-co/tree/dev).
3. Check that the README file has been completed. It should include the commands supported by the bot and a walkthrough of how to use these commands.

**Comment by amoghjos** [comment]
Hi @ramikham, the task does not follows the styleguide

**Comment by amoghjos** [comment]
Hi @ramikham, the link you have provided does not work. Please check :)
