### ISSUE TITLE
As a scheduler I would like to add TaskBot to discord server so that I can interact with it on #toDos channel

### ISSUE THREAD

**Issue by Mgeraci19** [xlab-classes/cse442-spring2022-team-terms-co#78]
**Acceptance tests**

_Test #1_
(1)Enter a discord server that you wish to add the bot to
(2) Invite the bot to this discord server using the link: 
https://discord.com/oauth2/authorize?client_id=945410708848386169&scope=bot
(3) Verify that the bot has joined the server
(4) Verify bot creates new channel with the command `start!`
(5) Verify that bot can be interacted with on #toDos

**Comment by amoghjos** [comment]
Same issue as #83
