### ISSUE TITLE
As a user, I would like to be shown the list of the commands that the bot supports when I type “/commands” so that I can refer back to the commands format.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#79]
**Task Tests**

_Test 1:_
1. Go to the discord server containing the task-bot
2. Send a message of the form "/commands"
3. Verify that the bot replies with a drop-down menu containing the commands it supports.

**Comment by amoghjos** [comment]
I was unable to test the user story on the PROD server and the user story does not follow the styleguide. Please fix!
