### ISSUE TITLE
As a scheduler, I want to mark a task as completed so that it no longer appears on the tasklist

### ISSUE THREAD

**Issue by Mgeraci19** [xlab-classes/cse442-spring2022-team-terms-co#8]
**Acceptance tests**

*Test #1*
1) Run main.py on a terminal
(2) Enter a discord server or create one using the + button in the bottom left of discord
(3) Invite the discord bot to the server using link "https://discord.com/api/oauth2/authorize?client_id=945410708848386169&permissions=75776&scope=bot%20applications.commands"
(4) Add a task by sending a message of the form "Remind me to do thing one at 2pm"
(5) Using the id sent back by the bot send a message of the form "Completed task id"
(5) Verify that the bot sends a message back indicating that that task is complete

*Test #1*
1) Run main.py on a terminal
(2) Enter a discord server or create one using the + button in the bottom left of discord
(3) Invite the discord bot to the server using link "https://discord.com/api/oauth2/authorize?client_id=945410708848386169&permissions=75776&scope=bot%20applications.commands"
(5) Send a message of the form "Completed task -1"
(5) Verify that the bot sends a message back indicating that that input is invalid

**Comment by amoghjos** [comment]
the user story was moved to completed but its task is still in progress. Why?

**Comment by amoghjos** [comment]
All tasks are completed

**Comment by amoghjos** [comment]
Test 1 is repeated
