### ISSUE TITLE
As a scheduler, I want to go to the landing page so that I can easily add TaskBot to Discord

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#80]
**Acceptance Tests**

_Test #1_
1) Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static/
2) Follow instructions and add TaskBot to Discord
3) Verify that the bot is added

**Comment by amoghjos** [comment]
Hi @snigui, the user story does not follow styleguide

**Comment by amoghjos** [comment]
@snigui the issue still does not follow the styleguide, i understand that you completed it and I can move it close but it does need to follow the styleguide

**Comment by snigui** [comment]
i made it follow the guide, can i move it to completed now?
