### ISSUE TITLE
As a scheduler I want to see a useful 'Landing Page' with instructions so that I can understand how to use the bot better

### ISSUE THREAD

**Issue by tanviekirane** [xlab-classes/cse442-spring2022-team-terms-co#81]
Acceptance Test:

_Test 1_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static
2. Click on the "Add Bot now!" on the navigation bar
3. Log into Discord & add a server you want to use the bot in
4. Verify that the bot is online in the server
5. Type "remind me to eat at 9pm"
6. Verify the bot responds with an affirmative message

_Test 2_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static
2. Scroll down to 'Learn More' or click this option on the navigation bar
3. Read the instructions & watch the demo video to learn more about the bot, click on the "click here to add bot" link under the video
4. Log into Discord & add a server you want to use the bot in
5. Verify that the bot is online in the server
6. Type "remind me to eat at 9pm"
7. Verify the bot responds with an affirmative message

**Comment by amoghjos** [comment]
Hi @tanviekirane, this issue is the same as #80. Please double check

**Comment by tanviekirane** [comment]
#80 was not actually assigned & is from last week. This user story ties up with #82 and requirements in the doc you sent for Sprint 3
