### ISSUE TITLE
Develop a Landing Page that helps user setup the bot in their server & understand the functionality of the bot

### ISSUE THREAD

**Issue by tanviekirane** [xlab-classes/cse442-spring2022-team-terms-co#82]
**Task Tests:**

_Test 1_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static
2. Click on the "Add Bot now!" on the navigation bar
3. Log into Discord & add a server you want to use the bot in
4. Verify that the bot is online in the server
5. Start with a message for a task of eating for example as "remind me to eat at 9pm"
6. Verify the bot responds with an affirmative message

_Test 2_

1. Go to https://www-student.cse.buffalo.edu/CSE442-542/2022-Spring/cse-442s/cse442-spring2022-team-terms-co/static
2. Go through the page (either scroll down or click on the options on the navigation bar
3. Specifically, go to the 'Learn More' tab and watch the quick demo video to see a functional demo of the bot & read instructions to set up the bot
4. Follow the steps and verify the bot is online in your server & responds to a "remind me to sleep at 10pm" message
5. Verify that the bot responds with an affirmative message

**Comment by amoghjos** [comment]
Duplicate to #80. The task does not follows style guide.

**Comment by tanviekirane** [comment]
I haven't written the final task tests yet since this is due Wednesday
