### ISSUE TITLE
The TaskBot should have a command to make new channel made upon connection

### ISSUE THREAD

**Issue by snigui** [xlab-classes/cse442-spring2022-team-terms-co#83]
**Task Tests**

*Test #1*
1) Make new TaskBot and verify new Token is created
2) Make new channel upon connection with `start!`
3) Verify new channel is called #todos

**Comment by amoghjos** [comment]
Hi @snigui, can you provide some more details in your task tests. For example, how do we create a task bot? Should I visit a link to do that....

Moreover, I tested your code in PROD but it does not seems to be working, so please ensure that your tasks work in the MAIN branch. Let me know in Discord when the issue are resolved.
