### ISSUE TITLE
More helpful feedback when an error occurs or a wrong message is sent

### ISSUE THREAD

**Issue by Eliwash73** [xlab-classes/cse442-spring2022-team-terms-co#84]
**Acceptance Tests:**

_Test 1:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed task 1’
6. send the message ‘delete 4’ to the bot
7. verify in the message sent back is:
    
![Untitled (7).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/979e4bce-49c3-4c9b-bd3d-7e758a06546b)

_Test 2:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed task 1’
6. send the message ‘delete task 4’ to the bot
7. verify in the message sent back is:
    
![Untitled (8).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/ff41d45b-06b1-4101-bc8e-4114a1826474)

_Test 3:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed 1’
6. verify in the message sent back is:
    
![Untitled (9).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/1812414f-0c7c-4388-b71d-4c3ad314239e)

_Test 4:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed task 6’
6. verify in the message sent back is:
    
![Untitled (10).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/d43e93df-339d-4242-abb4-719821856047)

_Test 5:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘completed task’
6. verify in the message sent back is:
    
![Untitled (11).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/59745f0e-255e-4c3b-a4f3-66df4cbe45be)

_Test 6:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. send the message ‘remind me to cook at’
5. verify in the message sent back is:
    
![Untitled (12).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/bd68928c-4dfb-4e47-97dd-a075e5c1b7af)
    

_Test 7:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. send the message ‘remind me to cook at 5pm’
5. send the message ‘edit 1: cook at 4:45pm’
6. verify in the message sent back is:
    
![Untitled (13).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/42386641-9962-48bd-b2fe-fe13653bbfa9)
    

_Test 8:_

1. go to [https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py](https://replit.com/@thewashcycle/WellgroomedBuzzingEllipses#main.py)
2. Paste bot token in the variable named TOKEN on line 12
3. click run and open discord server with the bot enabled
4. Type in several tasks:
    1. ‘remind me to cook at 4pm’
    2. ’remind me to workout at 5pm’
    3. ‘remind me to eat dinner at 6pm’
5. send the message ‘edit 5 : run at 8:30am’
6. verify in the message sent back is:
    
![Untitled (14).png](https://images.zenhubusercontent.com/620adc8a1e7c25018ddbb509/ce5f3c19-c022-4cdb-90b9-26a12531cca3)

**Comment by amoghjos** [comment]
There is no user story associated with this task. The task does not follow the styleguide
