### ISSUE TITLE
Notify the user of an event they previously scheduled. Reminders should work on the Cheshire server.

### ISSUE THREAD

**Issue by ramikham** [xlab-classes/cse442-spring2022-team-terms-co#85]
**Acceptance Tests**

_Test 1: Scheduling a Task_
1. ssh into cheshire:
ssh <your_ubid>@cheshire.cse.buffalo.edu
cd /web/CSE442-542/2022-Spring/cse-442s
2. Go to directory of team
cd cse442-spring2022-team-terms-co
3. Type:
bash
. env/bin/activate
cd .files
python main.py
4. Add (if not previously added) the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot
5. Schedule a task like "remind me to finish my homework at 11:00am".
4. Wait for the bot to send you a notification at the time you scheduled your task.

_Test 2: Deleting a Task_
1. ssh into cheshire:
ssh <your_ubid>@cheshire.cse.buffalo.edu
cd /web/CSE442-542/2022-Spring/cse-442s
2. Go to directory of team
cd cse442-spring2022-team-terms-co
3. Type:
bash
. env/bin/activate
cd .files
python main.py
4. Add (if not previously added) the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot.
5. Schedule a task like "remind me to finish my homewok at 11:00am". That task should have a task_ID = 1
6. Delete the task just scheduled by typing "Delete 1".
7. Make sure that the bot sends no notification at the time you scheduled the deleted task.

_Test 3: Completing a Task_
1. ssh into cheshire:
ssh <your_ubid>@cheshire.cse.buffalo.edu
cd /web/CSE442-542/2022-Spring/cse-442s
2. Go to directory of team
cd cse442-spring2022-team-terms-co
3. Type:
bash
. env/bin/activate
cd .files
python main.py
4. Add (if not previously added) the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot.
5. Schedule a task like "remind me to finish my homewok at 11:00am". That task should have a task_ID
6. Mark that task as completed by typing "completed task_ID".
7. Make sure that the bot sends no notification at the time you scheduled the completed task.

**Comment by amoghjos** [comment]
The task does not follow style guide

**Comment by amoghjos** [comment]
Hi @ramikham, this task does not follow the style guide, please resolve this issue, remove the "revision" label, and move it back to completed. Let me know if you have any questions :)
