### ISSUE TITLE
Associate all of the commands with the bot with its specific user id

### ISSUE THREAD

**Issue by Mgeraci19** [xlab-classes/cse442-spring2022-team-terms-co#87]
**Tasks Test**

_Task Tests_

Test #1
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/11c40a85-74fa-4787-8f18-a471cfd9d166)
1) ssh into cheshire
`ssh <your_ubid>@cheshire.cse.buffalo.edu`
`cd /web/CSE442-542/2022-Spring/cse-442s`
2) go to directory of team
`cd cse442-spring2022-team-terms-co`
3) type:
`bash`
`. env/bin/activate`
`cd .files`
`python main.py`
4) Add the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot
(5) Add a task of form "Remind me to do thing one at 3pm"
(6) Send a message of the form "userview" to see the id's of each message
(7) Send a message of the form completed task "id"
(8) Send a message of the form "userview"
(9) Verify that the task of that id is seen in a completed section

*Test #2*
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/11c40a85-74fa-4787-8f18-a471cfd9d166)
1) ssh into cheshire
`ssh <your_ubid>@cheshire.cse.buffalo.edu`
`cd /web/CSE442-542/2022-Spring/cse-442s`
2) go to directory of team
`cd cse442-spring2022-team-terms-co`
3) type:
`bash`
`. env/bin/activate`
`cd .files`
`python main.py`
4) Add the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot
(5) Add a task of form "Remind me to do thing one at 3pm"
(6) Send a message of the form "userview" to see the id's of each message
(7) Send a message of the form deleted task "id"
(8) Send a message of the form "userview"
(9) Verify that the task of that id is not seen in the completed section

*Test #3*
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/11c40a85-74fa-4787-8f18-a471cfd9d166)
1) ssh into cheshire
`ssh <your_ubid>@cheshire.cse.buffalo.edu`
`cd /web/CSE442-542/2022-Spring/cse-442s`
2) go to directory of team
`cd cse442-spring2022-team-terms-co`
3) type:
`bash`
`. env/bin/activate`
`cd .files`
`python main.py`
4) Add the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot
(5) Add a task of form "Remind me to do thing one at 3pm"
(6) Send a message of the form "userview" to see the id's of each message
(7) Send a message of the form edit id :  Remind me to not do a thing at 3pm
(8) Send a message of the form "userview"
(9) Verify that the edit is reflected in the inProgress section of view

*Test #4*
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/11c40a85-74fa-4787-8f18-a471cfd9d166)
1) ssh into cheshire
`ssh <your_ubid>@cheshire.cse.buffalo.edu`
`cd /web/CSE442-542/2022-Spring/cse-442s`
2) go to directory of team
`cd cse442-spring2022-team-terms-co`
3) type:
`bash`
`. env/bin/activate`
`cd .files`
`python main.py`
4) Add the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot
(5) Add a task of form "Remind me to do thing one"
(6) Send a messag of the form "9PM"
(7) Send a message of the form "userview" to see the id's of each message
(8)Verify that the task appears in progress

**Comment by amoghjos** [comment]
I will test in PROD

**Comment by amoghjos** [comment]
Hi @Mgeraci19, the task tests mentions that we are testing them in DEV, but they need to be tested in PROD, so please make those changes.

**Comment by amoghjos** [comment]
Hi @Mgeraci19, the task does not follow styleguide

![Screenshot 2022-04-15 at 2.24.30 PM.png](https://images.zenhubusercontent.com/6026e197d70abb4c93af3aa0/51c70639-092d-4fde-b508-6dd5cd1bf358)
