### ISSUE TITLE
Overdue tasks should be seen in the overdue section of view

### ISSUE THREAD

**Issue by Mgeraci19** [xlab-classes/cse442-spring2022-team-terms-co#88]
**Task tests**

*Test #1*
![image.png](https://images.zenhubusercontent.com/605b5b1f0fab1ad2920e4409/11c40a85-74fa-4787-8f18-a471cfd9d166)
1) ssh into cheshire
`ssh <your_ubid>@cheshire.cse.buffalo.edu`
`cd /web/CSE442-542/2022-Spring/cse-442s`
2) go to directory of team
`cd cse442-spring2022-team-terms-co`
3) type:
`bash`
`. env/bin/activate`
`cd .files`
`python main.py`
4) Add the discord bot to your server using the link: https://discord.com/api/oauth2/authorize?client_id=945841657193041970&permissions=8&scope=bot
(5) Add a task of form "Remind me to do thing one at 3pm"
(6) Send a message of the form "userview" to see the id's of each message
(7) Wait untill after 3pm or untill after the time you specified
(8) Send a message of the form "userview"
(9) Verify that the task of that id is seen in an overdue section

**Comment by amoghjos** [comment]
does not follow style guide
