### ISSUE TITLE
As a scheduler I would like to call view to see my tasks that are due so that I can see how behind I am on my tasks

### ISSUE THREAD

**Issue by Mgeraci19** [xlab-classes/cse442-spring2022-team-terms-co#90]
**Acceptance tests**

*Test #1*
(1) Go to the discord server containing the task-bot
(2) Send a message of the form "Remind me to do a thing at 3pm"
(3) Send a message of the form "view" in order to get the id of that message at a time before 3pm
(4) Verify that the task appears in the in progress section of view

*Test #2*
(1) Go to the discord server containing the task-bot
(2) Send a message of the form "Remind me to do a thing at 3pm"
(3) Send a message of the form "view" in order to get the id of that message at a time before 3pm
(4) Send a message of the form "completed task id"
(4) Verify that the task appears in the in completed section of view

*Test #3*
(1) Go to the discord server containing the task-bot
(2) Send a message of the form "Remind me to do a thing at 3pm"
(3) Send a message of the form "view" in order to get the id of that message at a time before 3pm
(4) Wait until after 3pm or an alternate time that has already passed
(4) Verify that the task appears in the in overdue section of view

**Comment by amoghjos** [comment]
Does not follow styleguide
